title: Andrew Nesbitt
url: https://nesbitt.io
email: andrew@nesbitt.io
tagline: Software Engineer and Package Management Nerd
description: Package management and open source metadata expert. Building Ecosyste.ms, open datasets and tools for critical open source infrastructure.
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
