title: Andrew Nesbitt
url: https://nesbitt.io
email: andrew@ecosyste.ms
author:
  name: Andrew Nesbitt
  email: andrew@ecosyste.ms
tagline: Software Engineer and Package Management Nerd
description: Package management and open source metadata expert. Building Ecosyste.ms, open datasets and tools for critical open source infrastructure.
logo: /images/boxes.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/boxes.png
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives

jekyll-archives:
  enabled:
    - year
    - month
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'

llmstxt:
  full: true

exclude:
  - .ruby-lsp
