name: Update README

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

permissions: {}

concurrency:
  group: update-readme
  cancel-in-progress: true

jobs:
  update:
    name: Update README
    runs-on: ubuntu-latest
    permissions:
      contents: write # push changes
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - uses: ruby/setup-ruby@90be1154f987f4dc0fe0dd0feedac9e473aa4ba8 
        with:
          ruby-version: '3.4'

      - name: Update README
        run: rake readme

      - name: Commit changes
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          if ! git diff --quiet; then
            git add README.md
            git commit -m 'Update README with recent posts'
            git push "https://x-access-token:${GH_TOKEN}@github.com/${REPO}" HEAD
          fi
