name: Zizmor

on:
  push:
    branches: ["master"]
    paths:
      - '.github/workflows/**'
  pull_request:
    branches: ["master"]
    paths:
      - '.github/workflows/**'
  workflow_dispatch:

permissions: {}

concurrency:
  group: zizmor-${{ github.ref }}
  cancel-in-progress: true

jobs:
  zizmor:
    name: Audit workflows
    runs-on: ubuntu-latest
    permissions:
      contents: read # checkout
      security-events: write # upload sarif
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - uses: woodruffw/zizmor-action@cd50a61a3ca50b4ed1c2286a3b06f2f7e62ed2a9 # v1.4.0
        with:
          upload-sarif: true
